### ISSUE TITLE
should not  hardcode credentials in crypto/account/filekey.go:120 

### ISSUE THREAD

**Issue by HAOYUatHZ** [xuperchain/xuperunion#125]
**Brief of the issue**
credentials is hardcoded in crypto/account/filekey.go:120 
```
password := "jingbo is handsome!"
```

**Comment by HawkJing** [comment]
Nice question. In the original design, the user must type a **password** in order to create a local account or retrieve an account by a mnemonic.  This password + a const string will be used as a salt in the pbkdf2. But finally we think it may be a little complicated for the account create/retrieve procedure. So this **password** has fallen into darkness and we will consider release it in the next version.

**Comment by HAOYUatHZ** [comment]
thx for the explanation.
